cabal-version:      3.0
name:               agda-json
version:            0.1.0.0
build-type:         Simple
data-files:
  ../data/agda/*.agda
  test/resources/*.jsonl
  ../data/agda/agda-algebras-regressions/*
tested-with: GHC ==9.4.7, GHC ==9.10.3

library
  hs-source-dirs: src
  exposed-modules:
      AgdaJsonl.Run
      AgdaJsonl.Extract
      AgdaJsonl.Cli
      AgdaJsonl.StructAst
  build-depends:
      base >= 4.17.2.0 && < 5
    , Agda == 2.8.0
    , containers
    , directory
    , filepath
    , text
    , aeson
    , time
    , unordered-containers
  default-language: GHC2021
  ghc-options: -Wall -Wcompat -Wincomplete-uni-patterns -O0

executable agda-json
  main-is:          Main.hs
  hs-source-dirs:   app
  build-depends:
      base >= 4.17.2.0 && < 5
    , agda-json
  default-language: GHC2021
  ghc-options: -Wall -Wcompat -Wincomplete-uni-patterns -O0

executable agda-json-runner
  main-is:          Runner.hs
  hs-source-dirs:   app
  build-depends:
      base >= 4.18 && < 5
    , aeson
    , bytestring
    , directory
    , filepath
    , process
    , text
    , time
  default-language: GHC2021
  ghc-options: -Wall -Wcompat -Wincomplete-uni-patterns -O0 -threaded -rtsopts

test-suite agda-json-tests
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Spec.hs
  other-modules:
      Paths_agda_json
  build-depends:
      base >= 4.17.2.0 && < 5
    , aeson
    , bytestring
    , directory
    , filepath
    , text
    , tasty
    , tasty-hunit
    , agda-json
  default-language: GHC2021
  ghc-options: -Wall -Wcompat -Wincomplete-uni-patterns -O0
  build-tool-depends: agda-json:agda-json
  autogen-modules: Paths_agda_json
