#!/usr/bin/env python3
"""
agda_lib_metadata.py

Generate per-library metadata for Agda projects:

- local-modules.txt / .json
- external-modules.txt / .json
- dependency-graph.dot (from Agda --dependency-graph)

Usage (from agda-ai-prover repo root):

  python scripts/python/agda_lib_metadata.py /path/to/agda-algebras

or

  python scripts/python/agda_lib_metadata.py /path/to/agda-algebras \
    --lib-name agda-algebras \
    --libraries-file /path/to/libraries \
    --out-dir data/corpora-metadata/agda-algebras \
    --format txt
"""

import argparse
import os
import sys
import tempfile
import subprocess
import json
import shutil
import re
from pathlib import Path
from typing import List, Tuple, Set


# -------------------------------
# Tiny pure helpers
# -------------------------------

def is_git_url(s: str) -> bool:
    return s.startswith("git@") or "://" in s


def find_agda_lib_file(root: Path) -> Path | None:
    candidates = list(root.glob("*.agda-lib"))
    return candidates[0] if candidates else None


def parse_agda_lib(lib_file: Path) -> Tuple[str, List[Path]]:
    """
    Very small parser for .agda-lib file: we only care about name + include dirs.
    Pure, side-effect-free.
    """
    name: str | None = None
    include_dirs: List[Path] = []

    with lib_file.open("r", encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith("--"):
                continue
            if line.startswith("name:"):
                name = line.split(":", 1)[1].strip()
            elif line.startswith("include:"):
                # include: dir1 dir2 ...
                rest = line.split(":", 1)[1].strip()
                parts = [p for p in rest.split() if p]
                for part in parts:
                    include_dirs.append((lib_file.parent / part).resolve())

    if name is None:
        name = lib_file.stem

    if not include_dirs:
        include_dirs = [lib_file.parent.resolve()]

    return name, include_dirs


def scan_local_modules(include_dirs: List[Path]) -> Set[str]:
    """
    Scan the include dirs for *.agda / *.lagda* files and return the set of
    module names (e.g. Algebra.Base).
    """
    modules: Set[str] = set()

    def path_to_module(path: Path, inc_root: Path) -> str:
        rel = path.relative_to(inc_root)
        # Drop compound suffixes (.agda, .lagda.md, .lagda.rst, etc.)
        # Loop until there is no suffix left.
        while rel.suffix:
            rel = rel.with_suffix("")
        return ".".join(rel.parts)

    for inc in include_dirs:
        for pattern in ("*.agda", "*.lagda*", "*.lagda.*"):
            for path in inc.rglob(pattern):
                modules.add(path_to_module(path, inc))

    # Never treat our synthetic Everything as a "real" local module.
    modules.discard("Everything")
    return modules

# -------------------------------
# Agda module name sanity
# -------------------------------
_SEGMENT = r"[A-Za-z_][A-Za-z0-9_']*"
_MODULE_RE = re.compile(rf"^{_SEGMENT}(?:\.{_SEGMENT})*$")

def is_valid_agda_module_name(m: str) -> bool:
    """
    Best-effort validation of an Agda module name.
    Prevents obvious parse errors such as 'agda-algebras' coming from filenames.
    """
    return bool(_MODULE_RE.match(m))

def filter_valid_modules(mods: Set[str]) -> Set[str]:
    bad = sorted(m for m in mods if not is_valid_agda_module_name(m))
    if bad:
        print(
            "[warn] ignoring invalid module names (likely from filenames): "
            + ", ".join(bad[:20])
            + (" ..." if len(bad) > 20 else ""),
            file=sys.stderr,
        )
    return set(m for m in mods if is_valid_agda_module_name(m))


def generate_everything_module(
    lib_root: Path,
    include_dirs: List[Path],
    modules: Set[str],
    root_module_name: str = "MetadataEverything",
) -> Tuple[Path, List[str], str]:
    """
    Generate a temporary <root_module_name>.agda that 'open import's all modules
    in the given set, under a temp dir rooted at lib_root.

    Returns (path_to_root_module, sorted_module_list, root_module_name).
    """
    tmp_dir = lib_root / ".agda-lib-metadata-tmp"
    tmp_dir.mkdir(exist_ok=True)

    everything = tmp_dir / f"{root_module_name}.agda"
    ordered = sorted(modules)

    with everything.open("w", encoding="utf-8") as f:
        f.write("-- Auto-generated by agda_lib_metadata.py\n")
        f.write(f"module {root_module_name} where\n\n")
        for m in ordered:
            f.write(f"open import {m}\n")

    return everything.resolve(), ordered, root_module_name


def parse_dependency_graph_modules(dot_file: Path, root_module_name: str | None) -> Set[str]:
    """
    Parse the Agda-generated DOT file and return the set of module names
    appearing as node labels, excluding the synthetic root module.
    """
    modules: Set[str] = set()

    with dot_file.open("r", encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()
            # Node lines look like: m0[label="Agda.Primitive"];
            if "[label=" in line:
                parts = line.split('"')
                if len(parts) >= 3:
                    label = parts[1]
                    if label:
                        modules.add(label)

    if root_module_name is not None:
        modules.discard(root_module_name)

    return modules


def write_list(path: Path, xs: List[str], fmt: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if fmt == "json":
        with path.open("w", encoding="utf-8") as f:
            json.dump(sorted(xs), f, indent=2, ensure_ascii=False)
    else:
        with path.open("w", encoding="utf-8") as f:
            for x in sorted(xs):
                f.write(x + "\n")


# -------------------------------
# Side-effecting helpers
# -------------------------------

def clone_repo(url: str) -> Path:
    tmp = Path(tempfile.mkdtemp(prefix="agda-lib-"))
    subprocess.check_call(["git", "clone", "--depth", "1", url, str(tmp)])
    return tmp


def run_agda_dependency_graph(
    everything: Path,
    libraries_file: Path | None,
    include_dirs: List[Path],
    out_dot: Path,
) -> None:
    """
    Invoke Agda with --dependency-graph to compute the transitive dependency
    closure of the synthetic root module.
    """
    agda = shutil.which("agda")
    if agda is None:
        raise FileNotFoundError(
            "Could not find 'agda' on PATH.\n"
            "Hint: run inside `nix develop` (so Agda is available), or install Agda,\n"
            "or update PATH so that `agda --version` works."
        )

    # IMPORTANT: do NOT pass --ignore-interfaces by default.
    # In Nix, stdlib lives in /nix/store and is read-only, and --ignore-interfaces
    # can force Agda to try to rewrite .agdai files there.
    cmd = [agda]

    if libraries_file is not None:
        cmd += ["--library-file", str(libraries_file)]

    # Include dirs for the library *and* the synthetic module.
    inc_dirs = list(include_dirs) + [everything.parent]

    for inc in inc_dirs:
        cmd += ["-i", str(inc)]

    cmd += [f"--dependency-graph={out_dot}", str(everything)]

    # For debugging:
    # print("Running:", " ".join(cmd), file=sys.stderr)

    subprocess.check_call(cmd)


# -------------------------------
# Main orchestration
# -------------------------------

def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate Agda library metadata.")
    parser.add_argument(
        "lib_root",
        help="Path to local Agda library root OR Git URL to clone",
    )
    parser.add_argument(
        "--lib-name",
        help="Logical Agda library name (defaults to .agda-lib name or directory name)",
    )
    parser.add_argument(
        "--libraries-file",
        help="Path to Agda 'libraries' file (defaults to $AGDA_LIBRARIES_FILE or tries to guess)",
    )
    parser.add_argument(
        "--out-dir",
        help="Output directory (defaults to data/corpora-metadata/<lib-name> under project root)",
    )
    parser.add_argument(
        "--format",
        choices=["txt", "json"],
        default="txt",
        help="Output format for module lists",
    )

    args = parser.parse_args(argv)

    script_path = Path(__file__).resolve()
    project_root = script_path.parent.parent.parent

    # 1. Resolve lib root (clone if necessary)
    if is_git_url(args.lib_root):
        lib_root = clone_repo(args.lib_root)
        cloned = True
    else:
        lib_root = Path(args.lib_root).expanduser().resolve()
        cloned = False

    # 2. Find .agda-lib and parse it (or fall back)
    agda_lib_file = find_agda_lib_file(lib_root)
    lib_name = args.lib_name
    include_dirs: List[Path] = []

    if agda_lib_file is not None:
        default_name, include_dirs = parse_agda_lib(agda_lib_file)
        if lib_name is None:
            lib_name = default_name
    else:
        include_dirs = [lib_root]
        if lib_name is None:
            lib_name = lib_root.name

    # 3. Libraries file resolution
    libraries_file: Path | None = None
    if args.libraries_file:
        libraries_file = Path(args.libraries_file).resolve()
    else:
        env = os.environ.get("AGDA_LIBRARIES_FILE")
        if env:
            libraries_file = Path(env).resolve()
        else:
            # Prefer the project-local libraries file written by flake shellHook.
            candidate = project_root / "agda-jang" / "agda" / "libraries"
            if candidate.is_file():
                libraries_file = candidate.resolve()
            else:
                candidate = lib_root / "libraries"
                if candidate.is_file():
                    libraries_file = candidate.resolve()

    # 4. Output dir
    if args.out_dir:
        out_dir = Path(args.out_dir).resolve()
    else:
        out_dir = project_root / "data" / "corpora-metadata" / lib_name

    # 5. Scan for all local modules and generate our own synthetic root module.
    all_local_modules = scan_local_modules(include_dirs)
    all_local_modules = filter_valid_modules(all_local_modules)
    everything, everything_mods, root_module_name = generate_everything_module(
        lib_root, include_dirs, all_local_modules, root_module_name="MetadataEverything"
    )

    # 6. Run Agda --dependency-graph starting from the synthetic root.
    dot_path = out_dir / "dependency-graph.dot"
    dot_path.parent.mkdir(parents=True, exist_ok=True)
    run_agda_dependency_graph(
        everything=everything,
        libraries_file=libraries_file,
        include_dirs=include_dirs,
        out_dot=dot_path,
    )

    # 7. Parse DOT file to get all dependent modules (excluding the synthetic root).
    dep_modules = parse_dependency_graph_modules(dot_path, root_module_name)

    # 8. Partition into local vs external based on our scanned module set
    local_modules = sorted(m for m in dep_modules if m in all_local_modules)
    external_modules = sorted(m for m in dep_modules if m not in all_local_modules)

    # 9. Write outputs
    write_list(out_dir / f"local-modules.{args.format}", local_modules, args.format)
    write_list(out_dir / f"external-modules.{args.format}", external_modules, args.format)
    write_list(out_dir / f"everything-modules.{args.format}",
               sorted(all_local_modules), args.format)

    # 10. Cleanup cloned repo if we cloned it
    if cloned:
        shutil.rmtree(lib_root, ignore_errors=True)

    print(f"[OK] Wrote metadata for {lib_name} to {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
